 = None
APPNAME = 'Peach'
AR = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\LIB.exe']
ARFLAGS = ['/nologo']
AR_TGT_F = '/OUT:'
ASSEMBLIES = ['mscorlib.dll']
ASS_ST = '/reference:C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.5.1\\%s'
BASENAME = 'win_x86'
BINDIR = 'output\\win_x86_release\\bin'
BUILDTAG = '0.0.0'
CC = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\CL.exe']
CCLNK_TGT_F = '/OUT:'
CC_NAME = 'msvc'
CC_SRC_F = ''
CC_TGT_F = ['/FC', '/c', '/Fo']
CFLAGS = ['/nologo']
CFLAGS_CONSOLE = ['/SUBSYSTEM:CONSOLE']
CFLAGS_CRT_MULTITHREADED = ['/MT']
CFLAGS_CRT_MULTITHREADED_DBG = ['/MTd']
CFLAGS_CRT_MULTITHREADED_DLL = ['/MD']
CFLAGS_CRT_MULTITHREADED_DLL_DBG = ['/MDd']
CFLAGS_NATIVE = ['/SUBSYSTEM:NATIVE']
CFLAGS_POSIX = ['/SUBSYSTEM:POSIX']
CFLAGS_WINDOWS = ['/SUBSYSTEM:WINDOWS']
CFLAGS_WINDOWSCE = ['/SUBSYSTEM:WINDOWSCE']
CFLAGS_cshlib = []
CL = ''
CPPFLAGS = ['/Z7', '/W4', '/WX']
CPPFLAGS_debug = ['/MTd', '/Od']
CPPFLAGS_release = ['/MT', '/Ox']
CPPPATH_ST = '/I%s'
CSDEBUG = 'pdbonly'
CSDOC = True
CSFLAGS = ['/noconfig', '/nologo', '/nostdlib+', '/warn:4', '/define:PEACH', '/errorreport:prompt', '/warnaserror', '/nowarn:1591']
CSFLAGS_debug = ['/define:DEBUG;TRACE']
CSFLAGS_release = ['/define:TRACE', '/optimize+']
CSPLATFORM = 'x86'
CS_NAME = 'csc'
CXX = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\CL.exe']
CXXFLAGS = ['/nologo']
CXXFLAGS_CONSOLE = ['/SUBSYSTEM:CONSOLE']
CXXFLAGS_CRT_MULTITHREADED = ['/MT']
CXXFLAGS_CRT_MULTITHREADED_DBG = ['/MTd']
CXXFLAGS_CRT_MULTITHREADED_DLL = ['/MD']
CXXFLAGS_CRT_MULTITHREADED_DLL_DBG = ['/MDd']
CXXFLAGS_NATIVE = ['/SUBSYSTEM:NATIVE']
CXXFLAGS_POSIX = ['/SUBSYSTEM:POSIX']
CXXFLAGS_WINDOWS = ['/SUBSYSTEM:WINDOWS']
CXXFLAGS_WINDOWSCE = ['/SUBSYSTEM:WINDOWSCE']
CXXFLAGS_com = ['/EHsc']
CXXFLAGS_cxxshlib = []
CXXFLAGS_pin = ['/MT', '/EHs-', '/EHa-', '/wd4530', '/Gy', '/Oi-', '/GR-', '/GS-', '/Zc:threadSafeInit-', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin\\gen', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\stlport\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\libstdc++\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\arch-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi\\asm-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\components\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-ia32\\include\\xed', '/FIinclude/msvc_compat.h']
CXXLNK_TGT_F = '/OUT:'
CXX_NAME = 'msvc'
CXX_SRC_F = ''
CXX_TGT_F = ['/FC', '/c', '/Fo']
DEFINES = ['_WINDOWS_H_PATH_=C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\um', 'WIN32', '_CRT_SECURE_NO_WARNINGS']
DEFINES_ST = '/D%s'
DEFINES_com = ['_WINDLL']
DEFINES_debug = ['DEBUG', '_DEBUG']
DEFINES_pin = ['TARGET_WINDOWS', 'BIGARRAY_MULTIPLIER=1', '__PIN__=1', 'PIN_CRT=1', '_HAS_EXCEPTIONS=0', '__i386__', 'TARGET_IA32', 'HOST_IA32']
DEST_BINFMT = 'pe'
DEST_CPU = 'x86'
DEST_OS = 'win32'
DOCDIR = 'output\\win_x86_release\\doc'
EXTERNALS = {'com': {'STLIB': ['Ole32', 'OleAut32', 'Advapi32'], 'DEFINES': ['_WINDLL']}, 'network': {'HEADERS': ['winsock2.h'], 'STLIB': ['ws2_32']}, 'pin': {'CXXFLAGS': ['/MT', '/EHs-', '/EHa-', '/wd4530', '/Gy', '/Oi-', '/GR-', '/GS-', '/Zc:threadSafeInit-', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin\\gen', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\stlport\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\libstdc++\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\arch-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi\\asm-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\components\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-ia32\\include\\xed', '/FIinclude/msvc_compat.h'], 'LINKFLAGS': ['/EXPORT:main', '/ENTRY:Ptrace_DllMainCRTStartup@12', '/BASE:0x55000000', '/FORCE:MULTIPLE', '/INCREMENTAL:NO', '/IGNORE:4210', '/IGNORE:4217', '/IGNORE:4049', '/NODEFAULTLIB', '/DYNAMICBASE', '/NXCOMPAT', 'crtbeginS.obj', 'kernel32.lib'], 'DEFINES': ['TARGET_WINDOWS', 'BIGARRAY_MULTIPLIER=1', '__PIN__=1', 'PIN_CRT=1', '_HAS_EXCEPTIONS=0', '__i386__', 'TARGET_IA32', 'HOST_IA32'], 'STLIBPATH': ['D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\lib', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\lib-ext', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\runtime\\pincrt', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-ia32\\lib'], 'STLIB': ['pin', 'xed', 'pincrt']}}
EXTERNALS_x64 = {'com': {'STLIB': ['Ole32', 'OleAut32', 'Advapi32'], 'DEFINES': ['_WINDLL']}, 'network': {'HEADERS': ['winsock2.h'], 'STLIB': ['ws2_32']}, 'pin': {'CXXFLAGS': ['/MT', '/EHs-', '/EHa-', '/wd4530', '/Gy', '/Oi-', '/GR-', '/GS-', '/Zc:threadSafeInit-', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin\\gen', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\stlport\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\libstdc++\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\arch-x86_64', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi\\asm-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\components\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-intel64\\include\\xed', '/FIinclude/msvc_compat.h'], 'LINKFLAGS': ['/EXPORT:main', '/ENTRY:Ptrace_DllMainCRTStartup', '/BASE:0xC5000000', '/FORCE:MULTIPLE', '/INCREMENTAL:NO', '/IGNORE:4210', '/IGNORE:4217', '/IGNORE:4049', '/NODEFAULTLIB', '/DYNAMICBASE', '/NXCOMPAT', 'crtbeginS.obj', 'kernel32.lib'], 'DEFINES': ['TARGET_WINDOWS', 'BIGARRAY_MULTIPLIER=1', '__PIN__=1', 'PIN_CRT=1', '_HAS_EXCEPTIONS=0', '__LP64__', 'TARGET_IA32E', 'HOST_IA32E'], 'STLIBPATH': ['D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\intel64\\lib', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\intel64\\lib-ext', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\intel64\\runtime\\pincrt', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-intel64\\lib'], 'STLIB': ['pin', 'xed', 'pincrt']}}
EXTERNALS_x86 = {'com': {'STLIB': ['Ole32', 'OleAut32', 'Advapi32'], 'DEFINES': ['_WINDLL']}, 'network': {'HEADERS': ['winsock2.h'], 'STLIB': ['ws2_32']}, 'pin': {'CXXFLAGS': ['/MT', '/EHs-', '/EHa-', '/wd4530', '/Gy', '/Oi-', '/GR-', '/GS-', '/Zc:threadSafeInit-', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\source\\include\\pin\\gen', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\stlport\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\libstdc++\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\arch-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\crt\\include\\kernel\\uapi\\asm-x86', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\components\\include', '/ID:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-ia32\\include\\xed', '/FIinclude/msvc_compat.h'], 'LINKFLAGS': ['/EXPORT:main', '/ENTRY:Ptrace_DllMainCRTStartup@12', '/BASE:0x55000000', '/FORCE:MULTIPLE', '/INCREMENTAL:NO', '/IGNORE:4210', '/IGNORE:4217', '/IGNORE:4049', '/NODEFAULTLIB', '/DYNAMICBASE', '/NXCOMPAT', 'crtbeginS.obj', 'kernel32.lib'], 'DEFINES': ['TARGET_WINDOWS', 'BIGARRAY_MULTIPLIER=1', '__PIN__=1', 'PIN_CRT=1', '_HAS_EXCEPTIONS=0', '__i386__', 'TARGET_IA32', 'HOST_IA32'], 'STLIBPATH': ['D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\lib', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\lib-ext', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\runtime\\pincrt', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-ia32\\lib'], 'STLIB': ['pin', 'xed', 'pincrt']}}
IMPLIB_ST = '/IMPLIB:%s'
INCLUDES = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\ATLMFC\\include', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\include', 'C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um', 'C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt', 'C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\shared', 'C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\um', 'C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\winrt', 'C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\cppwinrt']
LIBDIR = 'output\\win_x86_release\\bin'
LIBPATH = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\ATLMFC\\lib\\x86', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\lib\\x86', 'C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\lib\\um\\x86', 'C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.19041.0\\ucrt\\x86', 'C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.19041.0\\um\\x86', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\ATLMFC\\lib\\x86', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\lib\\x86', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\lib\\x86\\store\\references', 'C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.19041.0', 'C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.19041.0', 'C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319']
LIBPATH_ST = '/LIBPATH:%s'
LIB_ST = '%s.lib'
LINK = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\LINK.exe']
LINKFLAGS = ['/nologo', '/MANIFEST', '/NOLOGO', '/DEBUG', '/INCREMENTAL:NO', '/MACHINE:x86']
LINKFLAGS_cshlib = ['/DLL']
LINKFLAGS_cstlib = []
LINKFLAGS_cxxshlib = ['/DLL']
LINKFLAGS_pin = ['/EXPORT:main', '/ENTRY:Ptrace_DllMainCRTStartup@12', '/BASE:0x55000000', '/FORCE:MULTIPLE', '/INCREMENTAL:NO', '/IGNORE:4210', '/IGNORE:4217', '/IGNORE:4049', '/NODEFAULTLIB', '/DYNAMICBASE', '/NXCOMPAT', 'crtbeginS.obj', 'kernel32.lib']
LINK_CC = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\LINK.exe']
LINK_CXX = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\LINK.exe']
MCS = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn\\csc.exe']
MIDL = ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x86\\midl.exe']
MIDLFLAGS = ['/nologo', '/D', '_DEBUG', '/W1', '/char', 'signed', '/Oicf', '/win32']
MSBUILD = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\\\MSBuild\\Current\\Bin\\msbuild.exe']
MSVC_COMPILER = 'msvc'
MSVC_MANIFEST = True
MSVC_TARGETS = ['x86']
MSVC_VERSION = 16.11
MSVC_VERSIONS = ['msvc 16.11', 'msvc 16.8', 'msvc 15.0', 'msvc 14.0', 'msvc 12.0', 'msvc 11.0', 'msvc 10.0', 'wsdk 7.1']
MT = ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x86\\MT.exe']
MTFLAGS = ['/nologo']
OUTPUT = 'output'
PATH = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\\\Extensions\\Microsoft\\IntelliCode\\CLI', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\VC\\VCPackages', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\', 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\', 'C:\\Program Files (x86)\\HTML Help Workshop', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\Tools', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\devinit', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x86', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x86', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\\\MSBuild\\Current\\Bin', 'C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\', 'C:\\Python310\\Scripts\\', 'C:\\Python310\\', 'C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\dotnet\\', 'C:\\Strawberry\\c\\bin', 'C:\\Strawberry\\perl\\site\\bin', 'C:\\Strawberry\\perl\\bin', 'C:\\Program Files\\nodejs\\', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files\\Java\\jdk1.8.0_211\\bin', 'C:\\Program Files\\Git\\cmd', 'C', 'C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\', 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\', 'C:\\Ruby27-x64\\bin', 'C:\\Users\\Administrator\\.dotnet\\tools', 'C:\\Users\\Administrator\\AppData\\Local\\GitHubDesktop\\bin', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Microsoft VS Code\\bin', 'C:\\Program Files\\OpenSSH-Win64', 'C:\\Python27', 'C:\\Python27\\Scripts', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python39_64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python39_64\\Scripts', 'C:\\Users\\Administrator\\AppData\\Roaming\\npm', 'C:\\Program Files\\doxygen\\bin', '', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\VC\\Linux\\bin\\ConnectionManagerExe']
PEACH_PLATFORM_DLL = 'Peach.Pro.OS.Windows.dll'
PIN_VER = 'pin-3.19-98425-msvc-windows'
PKGDIR = 'output\\win_x86_release\\pkg'
PREFIX = 'output\\win_x86_release'
REFERENCE_ASSEMBLIES = 'C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.5.1'
RESGEN = ['C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\resgen.exe']
RESGENFLAGS = '/useSourcePath'
RES_ST = '/resource:%s'
RUN_NETFX = ''
STLIBPATH_ST = '/LIBPATH:%s'
STLIBPATH_pin = ['D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\lib', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\lib-ext', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\ia32\\runtime\\pincrt', 'D:\\work\\program\\protocol-fuzzer-ce-main\\3rdParty\\pin\\pin-3.19-98425-msvc-windows\\extras\\xed-ia32\\lib']
STLIB_ST = '%s.lib'
STLIB_com = ['Ole32', 'OleAut32', 'Advapi32']
STLIB_network = ['ws2_32']
STLIB_pin = ['pin', 'xed', 'pincrt']
SUBARCH = 'x86'
TARGET = 'win'
TARGET_FRAMEWORK = 'v4.5.1'
TARGET_FRAMEWORK_NAME = '.NET Framework 4.5.1'
TSC = ['C:\\Users\\Administrator\\AppData\\Roaming\\npm\\tsc.cmd']
TSC_FLAGS = ['--target', 'ES5', '--module', 'amd', '--removeComments', '--sourcemap']
VARIANT = 'release'
VARIANTS = ['debug', 'release']
VER_BRANCH = 1
VER_COMPANY = 'Peach Fuzzer, LLC'
VER_TEMPLATE = {'.cs': '\nusing System.Reflection;\nusing System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\n\n[assembly: AssemblyTitle("{TITLE}")]\n[assembly: AssemblyDescription("{DESC}")]\n[assembly: AssemblyConfiguration("{CONFIG}")]\n[assembly: AssemblyCompany("{COMPANY}")]\n[assembly: AssemblyProduct("{PRODUCT}")]\n[assembly: AssemblyCopyright("Copyright (c) {YEAR} {COMPANY}")]\n[assembly: AssemblyTrademark("")]\n[assembly: AssemblyCulture("")]\n[assembly: AssemblyVersion("{VER0}.{VER1}.{VER2}.{VER3}")]\n[assembly: AssemblyFileVersion("{VER0}.{VER1}.{VER2}.{VER3}")]\n[assembly: AssemblyInformationalVersion("{VER0}.{VER1}.{VER2}.{VER3} {VARIANT}")]\n', '.rc': '\n#include <winver.h>\nVS_VERSION_INFO VERSIONINFO\n FILEVERSION {VER0},{VER1},{VER2},{VER3}\n PRODUCTVERSION {VER0},{VER1},{VER2},{VER3}\n FILEFLAGS {FILEFLAGS} // 0, VS_FF_DEBUG, VS_FF_PRERELEASE\n FILEOS VOS_NT_WINDOWS32\n FILETYPE {FILETYPE} // VFT_DLL, VFT_APP\nBEGIN\n    BLOCK "StringFileInfo"\n    BEGIN\n        BLOCK "04090000"\n        BEGIN\n            VALUE "CompanyName", "{COMPANY}"\n            VALUE "FileDescription", "{DESC}"\n            VALUE "FileVersion", "{VER0}.{VER1}.{VER2}.{VER3}"\n            VALUE "LegalCopyright", "Copyright (c) {YEAR} {COMPANY}"\n            VALUE "InternalName", "{FILENAME}"\n            VALUE "OriginalFilename", "{FILENAME}"\n            VALUE "ProductName", "{PRODUCT}"\n            VALUE "ProductVersion", "{VER0}.{VER1}.{VER2}.{VER3} {VARIANT}"\n        END\n    END\n    BLOCK "VarFileInfo"\n    BEGIN\n        VALUE "Translation", 0x409, 0000\n    END\nEND\n', '.c': '\n#if defined(__cplusplus)\nextern "C" {{\n#endif\nconst char* g_buildTag = "{VER0}.{VER1}.{VER2}.{VER3}";\nconst char* g_buildDesc = "{PRODUCT} Version {VER0}.{VER1}.{VER2}.{VER3} ({CONFIG}), Built " __DATE__ " " __TIME__;\n#if defined(__cplusplus)\n}}\n#endif\n', '.cpp': '\n#if defined(__cplusplus)\nextern "C" {{\n#endif\nconst char* g_buildTag = "{VER0}.{VER1}.{VER2}.{VER3}";\nconst char* g_buildDesc = "{PRODUCT} Version {VER0}.{VER1}.{VER2}.{VER3} ({CONFIG}), Built " __DATE__ " " __TIME__;\n#if defined(__cplusplus)\n}}\n#endif\n', '.extra': '\n[assembly: {PROPERTY}({VALUE})]\n'}
WINRC = ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x86\\RC.exe']
WINRC_SRC_F = ''
WINRC_TGT_F = '/fo'
cprogram_PATTERN = '%s.exe'
cshlib_PATTERN = '%s.dll'
cstlib_PATTERN = '%s.lib'
cxxprogram_PATTERN = '%s.exe'
cxxshlib_PATTERN = '%s.dll'
cxxstlib_PATTERN = '%s.lib'
implib_PATTERN = '%s.lib'
supported_features = ['com', 'network', 'pin', 'tsc', 'paket', 'msbuild', 'test', 'zip', 'peach', 'win', 'c', 'cstlib', 'cshlib', 'cprogram', 'cxx', 'cxxstlib', 'cxxshlib', 'cxxprogram', 'fake_lib', 'nuget_lib', 'cs', 'debug', 'release', 'emit', 'vnum', 'subst', 'msbuild', 'flexnetls', 'install_task', 'win_x86']
variants = ['doc', 'win_x86_debug', 'win_x86_release', 'win_x64_debug', 'win_x64_release']
